### Библиотека NumPy

Библиотека для работы с многомерными массивами и матрицами в Python.  
**NumPy**(Numerical Python) — это библиотека с открытым исходным кодом, которая обеспечивает поддержку больших многомерных массивов и матриц, а также предоставляет множество математических функций для их обработки. Основным объектом NumPy является массив (ndarray), который позволяет эффективно хранить и обрабатывать данные.

In [5]:
# Создание массива
import numpy as np

# Создание одномерного массива
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

print()

# Создание двумерного массива
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[1 2 3 4 5]
[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]


In [7]:
# ndarray.ndim: число измерений массива.
print(f"Размерность: {array_2d.ndim}")

# ndarray.shape: размеры массива.
print(f"Форма: {array_2d.shape}") 

# ndarray.size: общее количество элементов в массиве.
print(f"Количество элементов: {array_2d.size}")

# ndarray.dtype: тип данных элементов массива.
print(f"Тип объекта: {array_2d.dtype}")

Размерность: 2
Форма: (2, 3)
Количество элементов: 6
Тип объекта: int32


In [9]:
# Доступ к элементам массива осуществляется с помощью индексов.
print(array_1d[0])
print(array_2d[1, 2])
print(array_2d[:, 1])

1
6
[2 5]


In [11]:
# арифметические операции над массивами.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [21]:
# функции для создания массивов заполненных нулями или единицами.
# Массив размером 3x3, заполненный нулями
zeros_array = np.zeros((3, 3))

# Массив размером 2x4, заполненный единицами
ones_array = np.ones((2, 4))

# Единичная матрица размером 3x3
eye_array = np.eye(3)

print(zeros_array, ones_array, eye_array, sep="\n\n")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
# агрегатные функции для вычисления статистических показателей
data = np.array([1, 2, 3, 4, 5])

# Среднее значение: Вывод: 3.0
print(np.mean(data))
# Медиана: Вывод: 3.0
print(np.median(data))
# Стандартное отклонение: Вывод: ~1.41421356
print(np.std(data))

3.0
3.0
1.4142135623730951


In [27]:
# умножения матриц используется функция np.dot() или оператор @.
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Умножение матриц
result = np.dot(matrix_a, matrix_b)
# Альтернативный способ
result_alt = matrix_a @ matrix_b

print(result)
print(result_alt)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Библиотека Pandas

**Pandas** — это библиотека с открытым исходным кодом, предназначенная для обработки и анализа данных. Она предоставляет две основные структуры данных:  
- **Series:** одномерный массив, который может хранить данные любого типа и имеет метки (индексы).
- **DataFrame:** двумерная таблица, состоящая из строк и столбцов, где каждый столбец представляет собой объект Series.

In [5]:
import pandas as pd

In [7]:
# Создание DataFrame из словаря
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [9]:
# Создание DataFrame из списка
data = [
    ['Alice', 25, 'New York'],
    ['Bob', 30, 'Los Angeles'],
    ['Charlie', 35, 'Chicago']
]

df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [11]:
# Добавление нового столбца:
df['Salary'] = [70000, 80000, 90000]
print(df)

      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   90000


In [13]:
# Удаление столбца
df.drop(columns=['City'], inplace=True)
print(df)

      Name  Age  Salary
0    Alice   25   70000
1      Bob   30   80000
2  Charlie   35   90000


In [15]:
# Фильтрация данных
filtered_df = df[df['Age'] > 30]
print(filtered_df)

      Name  Age  Salary
2  Charlie   35   90000


In [17]:
# Изменение значений
df.loc[0, 'Age'] = 26  # Изменение возраста для первой строки
print(df)

      Name  Age  Salary
0    Alice   26   70000
1      Bob   30   80000
2  Charlie   35   90000


In [19]:
# Сортировка данных
sorted_df = df.sort_values(by='Salary', ascending=False)
print(sorted_df)

      Name  Age  Salary
2  Charlie   35   90000
1      Bob   30   80000
0    Alice   26   70000
